/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 24 19:10:08 GMT 2019
 */

package Model;

import org.junit.Test;
import static org.junit.Assert.*;
import Model.Weather;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.Random;
import org.evosuite.runtime.System;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Weather_ESTest extends Weather_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      System.setCurrentTimeMillis((-2866L));
      Random.setNextRandom((-1));
      Weather weather0 = new Weather();
      double double0 = weather0.getSeasonDelay();
      assertEquals(0.1, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Random.setNextRandom(2147483645);
      Weather weather0 = new Weather();
      double double0 = weather0.getSeasonDelay();
      assertEquals(0.2, double0, 0.01);
      
      weather0.getSeasonDelay();
      weather0.getSeasonDelay();
      double double1 = weather0.getSeasonDelay();
      assertEquals((-0.20000000000000007), double1, 0.01);
  }
}
