/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 03 11:52:46 GMT 2019
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.util.MockGregorianCalendar;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ComparadorKm_ESTest extends ComparadorKm_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ComparadorKm comparadorKm0 = new ComparadorKm();
      MockGregorianCalendar mockGregorianCalendar0 = new MockGregorianCalendar((-794), 0, (-794), (-794), (-1202));
      Coordinate coordinate0 = new Coordinate((-1.0), 594.279640479);
      Cliente cliente0 = new Cliente("Cliente", "Cliente", "Cliente", "Cliente", "Cliente", mockGregorianCalendar0, coordinate0, (-1202), 0, 594.279640479);
      Cliente cliente1 = new Cliente();
      int int0 = comparadorKm0.compare(cliente0, cliente1);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ComparadorKm comparadorKm0 = new ComparadorKm();
      // Undeclared exception!
      try { 
        comparadorKm0.compare((Cliente) null, (Cliente) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ComparadorKm", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ComparadorKm comparadorKm0 = new ComparadorKm();
      Cliente cliente0 = new Cliente();
      MockGregorianCalendar mockGregorianCalendar0 = new MockGregorianCalendar((-1), (-1), (-1), (-1), (-1));
      Coordinate coordinate0 = new Coordinate((-1), (-1));
      Cliente cliente1 = new Cliente("3>OhD,Ex;", "3>OhD,Ex;", "3>OhD,Ex;", "3>OhD,Ex;", "3>OhD,Ex;", mockGregorianCalendar0, coordinate0, (-1), (-1), (-1));
      int int0 = comparadorKm0.compare(cliente1, cliente0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ComparadorKm comparadorKm0 = new ComparadorKm();
      Cliente cliente0 = new Cliente();
      int int0 = comparadorKm0.compare(cliente0, cliente0);
      assertEquals((-1), int0);
  }
}
