/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 24 19:21:16 GMT 2019
 */

package View.ViewModel;

import org.junit.Test;
import static org.junit.Assert.*;
import View.ViewModel.NewLogin;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class NewLogin_ESTest extends NewLogin_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NewLogin newLogin0 = new NewLogin((String) null, (String) null);
      String string0 = newLogin0.getUser();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      NewLogin newLogin0 = new NewLogin("grV'D?z&vW?8p", "HAYA");
      String string0 = newLogin0.getUser();
      assertEquals("HAYA", newLogin0.getPassword());
      assertEquals("grV'D?z&vW?8p", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      NewLogin newLogin0 = new NewLogin((String) null, (String) null);
      String string0 = newLogin0.getPassword();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      NewLogin newLogin0 = new NewLogin("", "yAAGV");
      String string0 = newLogin0.getPassword();
      assertEquals("yAAGV", string0);
      assertEquals("", newLogin0.getUser());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      NewLogin newLogin0 = new NewLogin("", "");
      String string0 = newLogin0.getPassword();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      NewLogin newLogin0 = new NewLogin("", "");
      String string0 = newLogin0.getUser();
      assertEquals("", string0);
  }
}
