/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 03 11:51:34 GMT 2019
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CarroGasolina_ESTest extends CarroGasolina_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Coordinate coordinate0 = new Coordinate(751.76817089, 1033.441132478);
      CarroGasolina carroGasolina0 = new CarroGasolina();
      List<ParDatas> list0 = carroGasolina0.getDatasAlugueres();
      CarroGasolina carroGasolina1 = new CarroGasolina("/OK", "/OK", "ParDatas", 549, (-1788.2021364), 751.76817089, 549, coordinate0, false, 549, list0);
      CarroGasolina carroGasolina2 = carroGasolina1.clone();
      assertEquals(549, carroGasolina2.getAutonomia());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CarroGasolina carroGasolina0 = new CarroGasolina();
      List<ParDatas> list0 = carroGasolina0.getDatasAlugueres();
      CarroGasolina carroGasolina1 = new CarroGasolina("}nN", "}nN", "}nN", (-1), 0.0, 2041.262165678, 0, (Coordinate) null, true, (-1), list0);
      CarroGasolina carroGasolina2 = carroGasolina1.clone();
      assertEquals((-1), carroGasolina2.getVelocidade());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Coordinate coordinate0 = new Coordinate(1264.27029562, 1264.27029562);
      LinkedList<ParDatas> linkedList0 = new LinkedList<ParDatas>();
      CarroGasolina carroGasolina0 = new CarroGasolina("Weather", (String) null, "Z]3oh+.N{;|Ns[1", (-1256), (-950.7), (-1256), 1, coordinate0, false, (-1256), linkedList0);
      CarroGasolina carroGasolina1 = carroGasolina0.clone();
      assertEquals((-950.7), carroGasolina1.getPreco(), 0.01);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Coordinate coordinate0 = new Coordinate(292.041385430077, 0);
      LinkedList<ParDatas> linkedList0 = new LinkedList<ParDatas>();
      CarroGasolina carroGasolina0 = new CarroGasolina((String) null, (String) null, "#%3{?8>XJAm-&;yo1_#", 0, 1844.627494291272, 1844.627494291272, 2086, coordinate0, false, 0, linkedList0);
      CarroGasolina carroGasolina1 = carroGasolina0.clone();
      assertEquals(0, carroGasolina1.getClassificacao());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Coordinate coordinate0 = new Coordinate(0.0, 0.15);
      LinkedList<ParDatas> linkedList0 = new LinkedList<ParDatas>();
      CarroGasolina carroGasolina0 = new CarroGasolina("", "", "r&`4Imn)Q`j'Vzr", (-1423), 0.15, 0.0, (-1724), coordinate0, false, 1, linkedList0);
      CarroGasolina carroGasolina1 = carroGasolina0.clone();
      assertEquals(0.15, carroGasolina1.getPreco(), 0.01);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      LinkedList<ParDatas> linkedList0 = new LinkedList<ParDatas>();
      CarroGasolina carroGasolina0 = new CarroGasolina("P^xIr[A7rE", "P^xIr[A7rE", "P^xIr[A7rE", (-2904), (-2904), (-2904), (-2904), (Coordinate) null, true, (-2904), linkedList0);
      // Undeclared exception!
      try { 
        carroGasolina0.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Veiculo", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Coordinate coordinate0 = new Coordinate(292.041385430077, 0);
      LinkedList<ParDatas> linkedList0 = new LinkedList<ParDatas>();
      CarroGasolina carroGasolina0 = new CarroGasolina((String) null, (String) null, "#%3{?8>XJAm-&;yo1_#", 0, 1844.627494291272, 1844.627494291272, 2086, coordinate0, false, 0, linkedList0);
      CarroGasolina carroGasolina1 = new CarroGasolina(carroGasolina0);
      // Undeclared exception!
      try { 
        carroGasolina1.equals(carroGasolina0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Veiculo", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Coordinate coordinate0 = new Coordinate(1517.23898431387, (-236.10238));
      CarroGasolina carroGasolina0 = null;
      try {
        carroGasolina0 = new CarroGasolina("", "", "", 1, 1771.56622, 1771.56622, 1, coordinate0, false, 1, (List<ParDatas>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Veiculo", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CarroGasolina carroGasolina0 = null;
      try {
        carroGasolina0 = new CarroGasolina((CarroGasolina) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Veiculo", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      CarroGasolina carroGasolina0 = new CarroGasolina();
      Object object0 = new Object();
      boolean boolean0 = carroGasolina0.equals(object0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CarroGasolina carroGasolina0 = new CarroGasolina();
      boolean boolean0 = carroGasolina0.equals(carroGasolina0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      CarroGasolina carroGasolina0 = new CarroGasolina();
      boolean boolean0 = carroGasolina0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Coordinate coordinate0 = new Coordinate(292.041385430077, 0);
      LinkedList<ParDatas> linkedList0 = new LinkedList<ParDatas>();
      CarroGasolina carroGasolina0 = new CarroGasolina((String) null, (String) null, "#%3{?8>XJAm-&;yo1_#", 0, 1844.627494291272, 1844.627494291272, 2086, coordinate0, false, 0, linkedList0);
      String string0 = carroGasolina0.toString();
      assertEquals("***** Carro a Gasolina *****\n*****    VE\u00CDCULO    *****\nMarca: null\nMatr\u00EDcula: null\nNIF do Propriet\u00E1rio: #%3{?8>XJAm-&;yo1_#\nVelocidade M\u00E9dia: 0\nPre\u00E7o Base por Km: 1844.627494291272\nConsumo: 1844.627494291272\nAutonomia: 2086\nPosi\u00E7\u00E3o (latitude e longitude): 292.041385, 0\nDispon\u00EDvel: false\nClassifica\u00E7\u00E3o: 0\n", string0);
  }
}
