/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 03 11:54:01 GMT 2019
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class NaoExistemAlugueresException_ESTest extends NaoExistemAlugueresException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NaoExistemAlugueresException naoExistemAlugueresException0 = new NaoExistemAlugueresException("=YB$0S!65l|\"z*u9vK");
  }
}
