/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 24 19:20:11 GMT 2019
 */

package View.ViewModel;

import org.junit.Test;
import static org.junit.Assert.*;
import View.ViewModel.RateOwnerCar;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RateOwnerCar_ESTest extends RateOwnerCar_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RateOwnerCar rateOwnerCar0 = new RateOwnerCar(0, 0);
      int int0 = rateOwnerCar0.getOwnerRate();
      assertEquals(0, rateOwnerCar0.getCarRate());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      RateOwnerCar rateOwnerCar0 = new RateOwnerCar(2889, 2889);
      int int0 = rateOwnerCar0.getOwnerRate();
      assertEquals(2889, rateOwnerCar0.getCarRate());
      assertEquals(2889, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      RateOwnerCar rateOwnerCar0 = new RateOwnerCar(0, 0);
      int int0 = rateOwnerCar0.getCarRate();
      assertEquals(0, rateOwnerCar0.getOwnerRate());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      RateOwnerCar rateOwnerCar0 = new RateOwnerCar(2889, 2889);
      int int0 = rateOwnerCar0.getCarRate();
      assertEquals(2889, rateOwnerCar0.getOwnerRate());
      assertEquals(2889, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      RateOwnerCar rateOwnerCar0 = new RateOwnerCar((-2237), (-2237));
      int int0 = rateOwnerCar0.getCarRate();
      assertEquals((-2237), rateOwnerCar0.getOwnerRate());
      assertEquals((-2237), int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      RateOwnerCar rateOwnerCar0 = new RateOwnerCar((-2237), (-2237));
      int int0 = rateOwnerCar0.getOwnerRate();
      assertEquals((-2237), int0);
      assertEquals((-2237), rateOwnerCar0.getCarRate());
  }
}
