/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 03 11:53:17 GMT 2019
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ComparadorAutonomia_ESTest extends ComparadorAutonomia_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ComparadorAutonomia comparadorAutonomia0 = new ComparadorAutonomia();
      Veiculo veiculo0 = new Veiculo();
      Coordinate coordinate0 = new Coordinate((-1), (-1));
      List<ParDatas> list0 = veiculo0.getDatasAlugueres();
      Veiculo veiculo1 = new Veiculo("ComparadorAutonomia", "ComparadorAutonomia", "ComparadorAutonomia", 3146, 0.4, (-1), (-397), coordinate0, false, (-1), list0);
      int int0 = comparadorAutonomia0.compare(veiculo1, veiculo0);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ComparadorAutonomia comparadorAutonomia0 = new ComparadorAutonomia();
      // Undeclared exception!
      try { 
        comparadorAutonomia0.compare((Veiculo) null, (Veiculo) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ComparadorAutonomia", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ComparadorAutonomia comparadorAutonomia0 = new ComparadorAutonomia();
      Coordinate coordinate0 = new Coordinate(1020, 1020);
      Veiculo veiculo0 = new Veiculo();
      LinkedList<ParDatas> linkedList0 = new LinkedList<ParDatas>();
      Veiculo veiculo1 = new Veiculo("JBPd \"roH!cCI", "JBPd \"roH!cCI", "JBPd \"roH!cCI", 1020, 1020, 1020, 1020, coordinate0, false, 1020, linkedList0);
      int int0 = comparadorAutonomia0.compare(veiculo1, veiculo0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ComparadorAutonomia comparadorAutonomia0 = new ComparadorAutonomia();
      Veiculo veiculo0 = new Veiculo();
      int int0 = comparadorAutonomia0.compare(veiculo0, veiculo0);
      assertEquals((-1), int0);
  }
}
