/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 24 19:06:22 GMT 2019
 */

package Model;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import Model.Parser;
import Model.UMCarroJa;
import java.nio.file.InvalidPathException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Parser_ESTest extends Parser_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      UMCarroJa uMCarroJa0 = new UMCarroJa();
      Parser parser0 = new Parser("INiI]38K_B2c", uMCarroJa0);
      Parser parser1 = new Parser("INiI]38K_B2c", uMCarroJa0);
      // Undeclared exception!
      try { 
        parser0.equals(parser1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Model.Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      UMCarroJa uMCarroJa0 = new UMCarroJa();
      Parser parser0 = null;
      try {
        parser0 = new Parser((String) null, uMCarroJa0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Parser parser0 = new Parser();
      Parser parser1 = new Parser();
      boolean boolean0 = parser0.equals(parser1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Parser parser0 = new Parser();
      boolean boolean0 = parser0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Parser parser0 = new Parser();
      boolean boolean0 = parser0.equals(parser0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      UMCarroJa uMCarroJa0 = new UMCarroJa();
      Parser parser0 = null;
      try {
        parser0 = new Parser("7.lS52ITPCe\"_GO", uMCarroJa0);
        fail("Expecting exception: InvalidPathException");
      
      } catch(InvalidPathException e) {
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Parser parser0 = new Parser();
      boolean boolean0 = parser0.equals("5in@dck)[a;8");
      assertFalse(boolean0);
  }
}
